import { Router } from 'express';
import { archiveProject, createProject, deleteProject, getProject, getProjects, restoreProject, updateProject } from '../controllers/projects';
import { removeMember, transferOwnership, updateMember } from '../controllers/projectMembers';
import { createInvitation, revokeInvitation } from '../controllers/projectInvitations';
import { createProjectTask, getProjectTasks } from '../controllers/projectTasks';
import { createProjectTag, deleteProjectTag, updateProjectTag } from '../controllers/projectTags';
import { asyncRoute } from './asyncRoute';

const router = Router();
router.get('/', asyncRoute(getProjects));
router.post('/', asyncRoute(createProject));
router.get('/:id', asyncRoute(getProject));
router.patch('/:id', asyncRoute(updateProject));
router.post('/:id/archive', asyncRoute(archiveProject));
router.post('/:id/restore', asyncRoute(restoreProject));
router.delete('/:id', asyncRoute(deleteProject));
router.get('/:projectId/tasks', asyncRoute(getProjectTasks));
router.post('/:projectId/tasks', asyncRoute(createProjectTask));
router.post('/:projectId/tags', asyncRoute(createProjectTag));
router.patch('/:projectId/tags/:tagId', asyncRoute(updateProjectTag));
router.delete('/:projectId/tags/:tagId', asyncRoute(deleteProjectTag));
router.post('/:projectId/invitations', asyncRoute(createInvitation));
router.delete('/:projectId/invitations/:invitationId', asyncRoute(revokeInvitation));
router.patch('/:projectId/members/:userId', asyncRoute(updateMember));
router.delete('/:projectId/members/:userId', asyncRoute(removeMember));
router.post('/:projectId/transfer-ownership', asyncRoute(transferOwnership));
export default router;
